CREATE TABLE IF NOT EXISTS players (
    id INTEGER,
    name TEXT,
    image TEXT,
    nationality TEXT,
    position TEXT,
    clubs TEXT,
    leagues TEXT,
    trophies TEXT,
    awards TEXT
);
INSERT INTO players VALUES (1,'L. Messi','assets/images/pl/messi.webp','argentina','rw','Barcelona, Paris Saint-Germain, Inter Miami','La Liga, Ligue 1, MLS','laLiga, championsLeague, ligue1, copaAmerica, worldCup','goldenBoot, ballonDor, uefaPoty'),
	(2,'C. Ronaldo','assets/images/pl/cristiano.webp','portugal','cf','Sporting CP, Manchester United, Real Madrid, Juventus, Al-Nassr','Primeira Liga, Premier League, La Liga, Serie A, Saudi Pro League','premierLeague, championsLeague, laLiga, serieA, euro','goldenBoot, ballonDor, uefaPoty'),
	(3,'A. Griezmann','assets/images/pl/griezmann.webp','france','cf','Real Sociedad, Atlético Madrid, Barcelona','La Liga','worldCup, europaLeague','empty'),
	(4,'A. Iniesta','assets/images/pl/iniesta.webp','spain','cm','Barcelona, Vissel Kobe, Emirates Club','La Liga, J1 League, UAE Pro League','worldCup, euro, laLiga, championsLeague','uefaPoty'),
	(5,'A. Morata','assets/images/pl/morata.webp','spain','cf','Atlético Madrid, Real Madrid, Chelsea, AC Milan, Juventus','La Liga, Premier League, Serie A','euro, laLiga, championsLeague, europaLeague, serieA','empty'),
	(6,'A. Shearer','assets/images/pl/shearer.webp','england','cf','Southampton, Blackburn, Newcastle','Premier League','premierLeague','empty'),
	(7,'A. Shevchenko','assets/images/pl/shevchenko.webp','ukraine','cf','AC Milan, Chelsea, Dynamo Kyiv','Premier League, Serie A, Premier Liga','championsLeague,  serieA','ballonDor'),
	(8,'Alisson','assets/images/pl/alisson.webp','brazil','gk','Internacional, AS Roma, Liverpool','Brazilian League, Serie A, Premier League','championsLeague, premierLeague, copaAmerica','empty'),
	(9,'Aubameyang','assets/images/pl/aubameyang.webp','gabon','cf','AC Milan, Saint-Étienne, Borussia Dortmund, Arsenal, Barcelona, Chelsea','Serie A, Ligue 1, Bundesliga, Premier League, La Liga','bundesliga','goldenBoot'),
	(10,'Beckenbauer','assets/images/pl/beckenbauer.webp','germany','cb','Bayern Munich, New York Cosmos, Hamburger SV','Bundesliga, NASL','bundesliga, championsLeague, worldCup, euro','ballonDor'),
	(11,'Cafu','assets/images/pl/cafu.webp','brazil','rb','São Paulo, Real Zaragoza, AS Roma, AC Milan','Brazilian League, Serie A, La Liga','championsLeague, serieA, worldCup, copaAmerica','empty'),
	(12,'Cuadrado','assets/images/pl/cuadrado.webp','colombia','rw','Independiente Santa Fe, Udinese, Fiorentina, Chelsea, Juventus','Serie A, Premier League','serieA','empty'),
	(13,'D. Alves','assets/images/pl/daniAlves.webp','brazil','rb','Barcelona, Juventus, Paris Saint-Germain, Sevilla, São Paulo, Bahia','La Liga, Serie A, Ligue 1, Brazilian League','laLiga, championsLeague, europaLeague, copaAmerica, serieA, ligue1','empty'),
	(14,'D. Bergkamp','assets/images/pl/bergkamp.webp','netherlands','cm','Ajax, Inter Milan, Arsenal','Eredivisie, Serie A, Premier League','premierLeague, serieA, europaLeague','empty'),
	(15,'D. Costa','assets/images/pl/douglasCosta.webp','brazil','lw','Grêmio, Shakhtar Donetsk, Bayern Munich, Juventus, LA Galaxy','Brazilian League, Ukrainian Premier League, Bundesliga, Serie A, MLS','bundesliga, serieA','empty'),
	(16,'D. Deschamps','assets/images/pl/deschamps.webp','france','cm','Nantes, Marseille, Bordeaux, Juventus, Chelsea, Valencia','Ligue 1, Serie A, Premier League, La Liga','championsLeague, serieA, worldCup, euro','empty'),
	(17,'P. Dybala','assets/images/pl/dybala.webp','argentina','cf','Instituto, Palermo, Juventus, AS Roma','Argentine Primera División, Serie A','serieA, worldCup','empty'),
	(18,'E. Dzeko','assets/images/pl/dzeko.webp','bosnia','cf','Željezničar, Teplice, Wolfsburg, Manchester City, AS Roma, Inter Milan, Fenerbahçe','Bosnian League, Czech First League, Bundesliga, Premier League, Serie A, Süper Lig','bundesliga, premierLeague','empty'),
	(19,'E. Can','assets/images/pl/emreCan.webp','germany','cm','Bayern Munich, Bayer Leverkusen, Borussia Dortmund, Juventus, Liverpool','Bundesliga, Serie A, Premier League','bundesliga, serieA, championsLeague','empty'),
	(20,'E. Cantona','assets/images/pl/cantona.webp','france','cf','Auxerre, Martigues, Olympique Marseille, Leeds United, Manchester United','Ligue 1, Premier League','premierLeague','empty'),
	(21,'E. Cavani','assets/images/pl/cavani.webp','uruguay','cf','Danubio, Palermo, Napoli, Paris Saint-Germain, Manchester United, Valencia, Boca Juniors','Uruguayan Primera División, Serie A, Ligue 1, Premier League, La Liga, Argentine Primera División','ligue1, copaAmerica','empty'),
	(22,'E. Haaland','assets/images/pl/haaland.webp','norway','cf','Bryne FK, Molde, RB Salzburg, Borussia Dortmund, Manchester City','Eliteserien, Austrian Bundesliga, Bundesliga, Premier League','championsLeague, premierLeague','uefaPoty, goldenBoot'),
	(23,'E. Hazard','assets/images/pl/hazard.webp','belgium','lw','Lille, Chelsea, Real Madrid','Ligue 1, Premier League, La Liga','premierLeague, laLiga, championsLeague, europaLeague','empty'),
	(24,'Ederson','assets/images/pl/ederson.webp','brazil','gk','Rio Ave, Benfica, Manchester City','Primeira Liga, Premier League','championsLeague, premierLeague, copaAmerica','empty'),
	(25,'F. Cannavaro','assets/images/pl/cannavaro.webp','italy','cb','Napoli, Parma, Inter Milan, Juventus, Real Madrid, Al-Ahli (UAE)','Serie A, La Liga, UAE Pro League','laLiga, europaLeague, worldCup','ballonDor, uefaPoty'),
	(26,'F. De Jong','assets/images/pl/frenkieDeJong.webp','netherlands','cm','Ajax, Barcelona','eredivisie, La Liga','laLiga','empty'),
	(27,'F. Kessie','assets/images/pl/kessie.webp','ivoryCoast','cm','Atalanta, Milan, Barcelona, Al-Ahli (SA)','Serie A, La Liga, Saudi Pro League','laLiga, serieA, afcon','empty'),
	(28,'F. Ribery','assets/images/pl/ribery.webp','france','lw','Boulogne, Ales, Stade Brest, Metz, Marseille, Bayern Munich, Fiorentina, Salernitana, Galatasaray','Ligue 1, Bundesliga, Serie A, Super Lig','bundesliga, championsLeague','uefaPoty'),
	(29,'F. Rijkaard','assets/images/pl/rijkaard.webp','netherlands','cm','Ajax, Sporting CP, Real Zaragoza, AC Milan','Eredivisie, Primeira Liga, La Liga, Serie A','serieA, euro, championsLeague','empty'),
	(30,'Fabinho','assets/images/pl/fabinho.webp','brazil','cm','Rio Ave, Monaco, Liverpool, Al-Ittihad','Primeira Liga, Ligue 1, Premier League, Saudi Pro League','premierLeague, championsLeague','empty'),
	(31,'G. Bale','assets/images/pl/bale.webp','wales','rw','Southampton, Tottenham Hotspur, Real Madrid, Los Angeles FC','Premier League, La Liga, MLS','laLiga, championsLeague','empty'),
	(32,'G. Buffon','assets/images/pl/buffon.webp','italy','gk','Parma, Juventus, Paris Saint-Germain','Serie A, Ligue 1','serieA, ligue1, worldCup, europaLeague','empty'),
	(33,'G. Higuain','assets/images/pl/higuain.webp','argentina','cf','River Plate, Real Madrid, Napoli, Juventus, AC Milan, Chelsea, Inter Miami','Argentine Primera División, La Liga, Serie A, Premier League, MLS','laLiga, serieA, europaLeague','empty'),
	(34,'G. Pique','assets/images/pl/pique.webp','spain','cb','Barcelona, Manchester United, Real Zaragoza','La Liga, Premier League','laLiga, championsLeague, premierLeague, worldCup, euro','empty'),
	(35,'G. Weah','assets/images/pl/weah.webp','liberia','cf','Monaco, Paris Saint-Germain, AC Milan, Chelsea, Manchester City , Marseille, Al-Jazira','Ligue 1, Serie A, Premier League, UAE Pro League','serieA','ballonDor, uefaPoty'),
	(36,'H. Stoichkov','assets/images/pl/stoichkov.webp','bulgaria','cf','CSKA Sofia, Barcelona, Parma, Al-Nassr, Kashiwa Reysol, Chicago Fire, D.C. United','Bulgarian League, La Liga, Serie A, Saudi Pro League, J1 League, MLS','laLiga, championsLeague','ballonDor, goldenBoot'),
	(37,'Hulk','assets/images/pl/hulk.webp','brazil','cf','Vitoria, Kawasaki Frontale, Consadole Sapporo, Tokyo Verdy, Porto, Zenit, Shanghai SIPG, Atlético Mineiro','Brazilian League, J1 League, Primeira Liga, Russian League, Chinese League','europaLeague','empty'),
	(38,'Isco','assets/images/pl/isco.webp','spain','cm','Málaga, Real Madrid, Sevilla, Real Betis','La Liga','laLiga, championsLeague','empty'),
	(39,'J. Cancelo','assets/images/pl/cancelo.webp','portugal','rb','Benfica, Valencia, Manchester City, Bayern Munich, Barcelona, Juventus, Inter Milan, Al-Hilal','Primeira Liga, La Liga, Premier League, Bundesliga, Serie A, Saudi Pro League','premierLeague, bundesliga, serieA, championsLeague','empty'),
	(40,'J. Cruyff','assets/images/pl/cruyff.webp','netherlands','cf','Ajax, Barcelona, Levante, Feyenoord','Eredivisie, La Liga','laLiga, championsLeague','ballonDor'),
	(41,'J. felix','assets/images/pl/felix.webp','portugal','cf','Benfica, Atlético Madrid, Chelsea, Barcelona','Primeira Liga, La Liga, Premier League','laLiga','empty'),
	(42,'J. Gomez','assets/images/pl/joeGomez.webp','england','cb','Charlton, Liverpool','Premier League','premierLeague, championsLeague','empty'),
	(43,'J. Kimmich','assets/images/pl/kimmich.webp','germany','rb','RB Leipzig, Stuttgart, Bayern Munich','Bundesliga','bundesliga, championsLeague','empty'),
	(44,'J. Zanetti','assets/images/pl/zanetti.webp','argentina','rb','Talleres, Banfield, Inter Milan','Argentine Primera División, Serie A','championsLeague, serieA, europaLeague','empty'),
	(45,'K. Benzema','assets/images/pl/benzema.webp','france','cf','Lyon, Real Madrid, Al-Ittihad','Ligue 1, La Liga, Saudi Pro League','championsLeague, laLiga, ligue1','ballonDor, uefaPoty'),
	(46,'K. De Bruyne','assets/images/pl/deBruyne.webp','belgium','cm','Genk, Chelsea, Werder Bremen, Wolfsburg, Manchester City','Jupiler Pro League, Premier League, Bundesliga','premierLeague, championsLeague','empty'),
	(47,'K. Koulibaly','assets/images/pl/koulibaly.webp','senegal','cb','Metz, Genk, Napoli, Chelsea, Al-Hilal','Jupiler Pro League, Serie A, Saudi Pro League','afcon','empty'),
	(48,'K. Mbappe','assets/images/pl/mbappe.webp','france','cf','Monaco, Paris Saint-Germain, Real Madrid','Ligue 1, La Liga','ligue1, worldCup','empty'),
	(49,'Kaka','assets/images/pl/kaka.webp','brazil','cm','São Paulo, AC Milan, Real Madrid, Orlando City','Brazilian League, Serie A, La Liga, MLS','serieA, championsLeague, laLiga, worldCup','ballonDor, uefaPoty'),
	(50,'L. Bonucci','assets/images/pl/bonucci.webp','italy','cb','Inter Milan, Treviso, Pisa, Bari, Juventus, AC Milan, Union Berlin, Fenerbahçe','Serie A, Bundesliga, Süper Lig','serieA, euro','empty'),
	(51,'L. Figo','assets/images/pl/figo.webp','portugal','cm','Sporting CP, Barcelona, Real Madrid, Inter Milan','Primeira Liga, La Liga, Serie A','laLiga, championsLeague, serieA','ballonDor, uefaPoty'),
	(52,'L. Matthäus','assets/images/pl/matthaus.webp','germany','cm','Borussia Mönchengladbach, Bayern Munich, Inter Milan, MetroStars','Bundesliga, Serie A, MLS','bundesliga, serieA, worldCup, euro, europaLeague','uefaPoty'),
	(53,'L. Modric','assets/images/pl/modric.webp','croatia','cm','Dinamo Zagreb, Zrinjski Mostar, Inter Zaprešić, Tottenham Hotspur, Real Madrid','Croatian League, Premier League, La Liga','laLiga, championsLeague','ballonDor, uefaPoty'),
	(54,'L. Sane','assets/images/pl/sane.webp','germany','lw','Schalke 04, Manchester City, Bayern Munich','Bundesliga, Premier League','premierLeague, bundesliga','empty'),
	(55,'L. Suarez','assets/images/pl/suarez.webp','uruguay','cf','Nacional, Groningen, Ajax, Liverpool, Barcelona, Atlético Madrid, Gremio, Inter Miami','Uruguayan Primera División, Eredivisie, Premier League, La Liga, Brazilian League, MLS','laLiga, championsLeague, copaAmerica','goldenBoot'),
	(56,'L. Yamal','assets/images/pl/yamal.webp','spain','rw','Barcelona','La Liga','euro, laLiga','empty'),
	(57,'Luuk De Jong','assets/images/pl/luukDeJong.webp','netherlands','cf','PSV Eindhoven, Borussia Mönchengladbach, Sevilla, Barcelona, Newcastle United, FC Utrecht.','Eredivisie, La Liga, Bundesliga, Premier League','europaLeague','empty'),
	(58,'M. Allister','assets/images/pl/macAllister.webp','argentina','cm','Argentinos Juniors, Boca Juniors, Brighton, Liverpool','Argentine Primera División, Premier League','copaAmerica, worldCup','empty'),
	(59,'M. Alonso','assets/images/pl/marcosAlonso.webp','spain','lb','Bolton, Fiorentina, Sunderland, Chelsea, Barcelona, Celta Vigo','La Liga, Premier League, Serie A','premierLeague, championsLeague, europaLeague, laLiga','empty'),
	(60,'M. De Ligt','assets/images/pl/deLigt.webp','netherlands','cb','Ajax, Juventus, Bayern Munich, Manchester United','Eredivisie, Serie A, Bundesliga, Premier League','bundesliga, serieA','empty'),
	(61,'M. Icardi','assets/images/pl/icardi.webp','argentina','cf','Sampdoria, Inter Milan, Paris Saint-Germain, Galatasaray','Serie A, Ligue 1, Süper Lig','ligue1','empty'),
	(62,'M. Neuer','assets/images/pl/neuer.webp','germany','gk','Bayern Munich, Schalke 04','Bundesliga','bundesliga, worldCup, championsLeague','empty'),
	(63,'M. Owen','assets/images/pl/owen.webp','england','cf','Liverpool, Real Madrid, Newcastle United, Manchester United, Stoke City','Premier League, La Liga','premierLeague, europaLeague','ballonDor'),
	(64,'M. Salah','assets/images/pl/salah.webp','egypt','rw','El Mokawloon, Basel, Chelsea, Fiorentina, Roma, Liverpool','Egyptian League, Premier League, Serie A, Swiss Super League','premierLeague, championsLeague','empty'),
	(65,'Malcom','assets/images/pl/malcom.webp','brazil','rw','Corinthians, Bordeaux, Zenit, Barcelona, Al-Hilal','Brazilian League, Ligue 1, La Liga, Russian League, Saudi Pro League','laLiga','empty'),
	(66,'Mandzukic','assets/images/pl/mandzukic.webp','croatia','cf','Dinamo Zagreb, Wolfsburg, Bayern Munich, Atlético Madrid, Juventus, Al-Duhail, AC Milan','Croatian League, Bundesliga, La Liga, Serie A, Qatar League','championsLeague, bundesliga, serieA','empty'),
	(67,'Maradona','assets/images/pl/maradona.webp','argentina','cf','Argentinos Juniors, Boca Juniors, Barcelona, Napoli, Sevilla, Newell''s Old Boys','Argentine Primera División, La Liga, Serie A','worldCup, serieA, europaLeague','empty'),
	(68,'Marcelo','assets/images/pl/marcelo.webp','brazil','lb','Fluminense, Real Madrid, Olympiacos','La Liga, Super League 1, Brazilian League','laLiga, championsLeague','empty'),
	(69,'M. Laudrup','assets/images/pl/laudrup.webp','denmark','cm','Lazio, Juventus, Barcelona, Real Madrid, Ajax, Vissel Kobe','Serie A, La Liga, J1 League, Eredivisie','laLiga, championsLeague, serieA','empty'),
	(70,'Mkhitaryan','assets/images/pl/mkhitaryan.webp','armenia','cm','Pyunik, Metalurh Donetsk, Shakhtar Donetsk, Borussia Dortmund, Manchester United, Arsenal, Roma, Inter Milan​','Armenian League, Ukrainian League, Premier League, Bundesliga, Serie A','serieA, europaLeague, conferenceLeague','empty'),
	(71,'Neymar','assets/images/pl/neymar.webp','brazil','lw','Santos FC, Barcelona, Paris Saint-Germain, Al-Hilal','La Liga, Brazilian League, Ligue 1, Saudi Pro League','laLiga, championsLeague, ligue1, copaAmerica','empty'),
	(72,'P. Lahm','assets/images/pl/lahm.webp','germany','rb','Bayern Munich, Stuttgart','Bundesliga','worldCup, bundesliga, championsLeague','empty'),
	(73,'P. Maldini','assets/images/pl/maldini.webp','italy','lb','AC Milan','Serie A','championsLeague, serieA','empty'),
	(74,'P. Nedved','assets/images/pl/nedved.webp','czechia','cm','Viktoria Plzen, Sparta Prague, Lazio, Juventus','Czech League, Serie A','serieA','ballonDor'),
	(75,'P. Pogba ','assets/images/pl/pogba.webp','france','cm','Juventus, Manchester United','Premier League, Serie A','serieA, europaLeague, worldCup','empty'),
	(76,'Pedri','assets/images/pl/pedri.webp','spain','cm','Las Palmas, Barcelona','La Liga','euro, laLiga','empty'),
	(77,'Pepe','assets/images/pl/pepe.webp','portugal','cb','Marítimo, Porto, Real Madrid, Besiktas','Primeira Liga, La Liga, Süper Lig','euro, laLiga, championsLeague','empty'),
	(78,'R. Baggio','assets/images/pl/baggio.webp','italy','cm','Vicenza, Fiorentina, Juventus, AC Milan, Bologna, Inter Milan, Brescia','Serie A','serieA, europaLeague','ballonDor, uefaPoty'),
	(79,'R. Gullit','assets/images/pl/gullit.webp','netherlands','cm','Feyenoord, PSV Eindhoven, AC Milan, Sampdoria, Chelsea','Eredivisie, Serie A, Premier League','euro, championsLeague, serieA','ballonDor'),
	(80,'R. Koeman','assets/images/pl/koeman.webp','netherlands','cb','Groningen, Ajax, Feyenoord, PSV Eindhoven, Barcelona','Eredivisie, La Liga','euro, championsLeague, laLiga','empty'),
	(81,'R. Lewandowski','assets/images/pl/lewandowski.webp','poland','cf','Znicz Pruszków, Lech Poznań, Borussia Dortmund, Bayern Munich, Barcelona','Poland League, Bundesliga, La Liga','championsLeague, laLiga, bundesliga','uefaPoty, goldenBoot'),
	(82,'R. Mahrez','assets/images/pl/mahrez.webp','algeria','rw','Le Havre, Leicester City, Manchester City, Al-Ahli','Ligue 1, Premier League, Saudi Pro League','afcon, championsLeague, premierLeague','empty'),
	(83,'A. Rabiot','assets/images/pl/rabiot.webp','france','cm','Toulouse, Paris Saint-Germain, Juventus, Marseille','Ligue 1, Serie A','ligue1, serieA','empty'),
	(84,'Rodri','assets/images/pl/rodri.webp','spain','cm','Villarreal, Atlético Madrid, Manchester City','La Liga, Premier League','euro, premierLeague, championsLeague','ballonDor'),
	(85,'Ronaldinho','assets/images/pl/ronaldinho.webp','brazil','lw','Grêmio, Paris Saint-Germain, Barcelona, Milan, Flamengo, Atlético Mineiro, Fluminense','Brazilian League, Serie A, La Liga, Ligue 1','copaAmerica, worldCup, championsLeague, laLiga, serieA','ballonDor, uefaPoty'),
	(86,'Ronaldo Nazário','assets/images/pl/ronaldo9.webp','brazil','cf','Cruzeiro, PSV Eindhoven, Barcelona, Inter Milan, Real Madrid, Milan, Corinthians','Brazilian League, La Liga, Serie A, Eredivisie','copaAmerica, worldCup, laLiga, europaLeague','ballonDor, uefaPoty, goldenBoot'),
	(87,'S. Busquets','assets/images/pl/busquets.webp','spain','cm','Barcelona, Inter Miami','La Liga, MLS','laLiga, championsLeague, worldCup, euro','empty'),
	(88,'S. Mane','assets/images/pl/mane.webp','senegal','lw','Metz, RB Salzburg, Southampton, Liverpool, Bayern Munich, Al-Nassr','Ligue 1, Bundesliga, Premier League, Saudi Pro League','afcon, championsLeague, premierLeague, bundesliga','empty'),
	(89,'S. Ramos','assets/images/pl/ramos.webp','spain','cb','Sevilla, Real Madrid, Paris Saint-Germain','La Liga, Ligue 1','laLiga, championsLeague, euro, worldCup, ligue1','empty'),
	(90,'Szczesny','assets/images/pl/szczesny.webp','poland','gk','Brentford, Arsenal, Roma, Juventus, Barcelona','Premier League, Serie A, La Liga','serieA','empty'),
	(91,'T. Abraham','assets/images/pl/abraham.webp','england','cf','Swansea, Aston Villa, Chelsea, Roma','Premier League, Serie A','europaLeague, championsLeague','empty'),
	(92,'T. Courtois','assets/images/pl/courtois.webp','belgium','gk','Genk, Atlético Madrid, Chelsea, Real Madrid','Jupiler Pro League, Premier League, La Liga','premierLeague, championsLeague, laLiga, europaLeague','empty'),
	(93,'T. Henry','assets/images/pl/henry.webp','france','cf','AS Monaco, Juventus, Arsenal, Barcelona, New York Red Bulls','Ligue 1, Serie A,Premier League, La Liga, MLS','ligue1, premierLeague, championsLeague, laLiga, euro, worldCup','goldenBoot'),
	(94,'V. Van Dijk','assets/images/pl/vanDijk.webp','netherlands','cb','Groningen, Celtic, Southampton, Liverpool','Eredivisie, Premier League, Scottish Premiership','premierLeague, championsLeague','empty'),
	(95,'Van Basten','assets/images/pl/vanBasten.webp','netherlands','cf','Ajax, AC Milan','Eredivisie, Serie A','serieA, championsLeague, euro','ballonDor, uefaPoty, goldenBoot'),
	(96,'W. Rooney','assets/images/pl/rooney.webp','england','cf','Everton, Manchester United, D.C. United, Derby','Premier League, MLS','premierLeague, championsLeague','empty'),
	(97,'Xavi','assets/images/pl/xavi.webp','spain','cm','Barcelona, Al-Sadd','La Liga, Qatar League','laLiga, championsLeague, worldCup, euro','empty'),
	(98,'Z. Ibrahimovic','assets/images/pl/ibrahimovic.webp','sweden','cf','Malmö FF, Ajax, Juventus, Inter Milan, Barcelona, AC Milan, Paris Saint-Germain, Manchester United, LA Galaxy','Allsvenskan, Eredivisie, Serie A, La Liga, Ligue 1, Premier League, MLS','serieA, laLiga, ligue1,  europaLeague','empty'),
	(99,'Z. Zidan','assets/images/pl/zidan.webp','france','cm','Cannes, Bordeaux, Juventus, Real Madrid','Ligue 1, Serie A, La Liga','serieA, laLiga, championsLeague, worldCup, euro','ballonDor, uefaPoty'),
	(100,'J. Bellingham','assets/images/pl/bellingham.webp','england','cm','Birmingham, Borussia Dortmund, Real Madrid','Bundesliga, La Liga','championsLeague, laLiga','empty'),
	(101,'Rivaldo','assets/images/pl/rivaldo.webp','brazil','cm','Santa Cruz, Mogi Mirim, Corinthians, Palmeiras, Deportivo La Coruña, Barcelona, AC Milan, Cruzeiro, Olympiacos, AEK Athens, Bunyodkor, São Paulo FC, Kabuscorp','Brazilian League, La Liga, Serie A, Greek Super League, Uzbek League, Angolan League','championsLeague, worldCup, copaAmerica, laLiga, serieA','ballonDor, uefaPoty');
